-- ============================================
-- E-Commerce Data Warehouse - Snowflake Setup
-- ============================================

-- 1. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


-- 2. Create Database
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;


-- 3. Create Schemas
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.RAW;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.ANALYTICS;


-- 4. Set Context
USE WAREHOUSE ECOMMERCE_WH;

USE DATABASE ECOMMERCE_DB;

USE SCHEMA RAW;


-- 5. Create Raw Tables

CREATE OR REPLACE TABLE CUSTOMERS (
    ID INTEGER,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    COUNTRY VARCHAR(100)
);


CREATE OR REPLACE TABLE PRODUCTS (
    ID INTEGER,
    NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    PRICE NUMBER(10,2)
);


CREATE OR REPLACE TABLE ORDERS (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    STATUS VARCHAR(50)
);


CREATE OR REPLACE TABLE ORDER_ITEMS (
    ID INTEGER,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    UNIT_PRICE NUMBER(10,2)
);
